const field = (name, type = "string", defaultValue = "", options = "", required = false, help = "") => ({
  name,
  type,
  default: String(defaultValue ?? ""),
  options: Array.isArray(options) ? options.join(",") : options,
  required,
  help,
});

const unsupported = (name, extra = [], common = [rootPath("/")]) => ({
  common,
  additional: extra,
  config: {
    name,
    local_sort: true,
    only_proxy: true,
    no_cache: false,
    no_upload: true,
    need_ms: false,
    default_root: "/",
    alert: "warning",
    only_indices: false,
    prefer_proxy: true,
    status: "metadata-only",
    note: "Driver metadata is copied for mount creation. Runtime behavior is still being ported to the SiYuan kernel JS environment.",
  },
});

const supported = (name, extra = [], common) => {
  const info = unsupported(name, extra, common);
  info.config.status = "ported";
  info.config.note = "Runtime behavior is wired through SiYuan /api/network/forwardProxy in the kernel plugin.";
  info.config.no_upload = false;
  info.config.only_proxy = false;
  info.config.prefer_proxy = false;
  return info;
};

const preferProxy = (info) => {
  info.config.prefer_proxy = true;
  return info;
};

const configPatch = (info, patch) => {
  Object.assign(info.config, patch);
  return info;
};

const text = (name, required = false, help = "") => field(name, "string", "", "", required, help);
const password = (name, required = false, help = "") => field(name, "password", "", "", required, help);
const bool = (name, defaultValue = false, help = "") => field(name, "bool", defaultValue, "", false, help);
const number = (name, defaultValue = "", required = false, help = "") => field(name, "number", defaultValue, "", required, help);
const float = (name, defaultValue = "", required = false, help = "") => field(name, "float", defaultValue, "", required, help);
const select = (name, options, defaultValue = "", required = false, help = "") => field(name, "select", defaultValue, options, required, help);
const rootPath = (defaultValue = "/") => field("root_folder_path", "string", defaultValue, "", false, "OpenList root folder path.");
const rootId = (defaultValue = "") => field("root_folder_id", "string", defaultValue, "", false, defaultValue ? `OpenList default root: ${defaultValue}` : "");

const metadataOnlyNames = [
  "139Yun",
  "Alias",
  "AutoIndex",
  "Azure Blob Storage",
  "BaiduPhoto",
  "CNB Releases",
  "ChaoXingGroupDrive",
  "Chunk",
  "Cloudreve V4",
  "Crypt",
  "Degoo",
  "Doubao",
  "DoubaoNew",
  "DoubaoShare",
  "FTP",
  "FebBox",
  "FeijiPan",
  "GitHub API",
  "GitHub Releases",
  "HalalCloud",
  "HalalCloudOpen",
  "ILanZou",
  "IPFS API",
  "KodBox",
  "LenovoNasShare",
  "MediaFire",
  "MediaTrack",
  "Mega_nz",
  "Misskey",
  "MoPan",
  "NeteaseMusic",
  "OpenListShare",
  "PikPakShare",
  "ProtonDrive",
  "Seafile",
  "Strm",
  "Teambition",
  "Teldrive",
  "Template",
  "Terabox",
  "ThunderBrowser",
  "ThunderBrowserExpert",
  "ThunderExpert",
  "ThunderX",
  "ThunderXExpert",
  "UrlTree",
  "WeiYun",
  "WoPan",
  "YandexDisk",
];

const withAliases = (map) => ({
  ...map,
  "115": map["115 Cloud"],
  "115Open": map["115 Open"],
  "115Share": map["115 Share"],
  "123": map["123Pan"],
  "123Open": map["123 Open"],
  "123Share": map["123PanShare"],
  "AliyunDrive": map.Aliyundrive,
  "AliyunDriveOpen": map.AliyundriveOpen,
  "AliyunDriveShare": map.AliyundriveShare,
  "OneDrive": map.Onedrive,
});

const driverNameOrder = [
  "SiYuanWorkspace",
  "Local",
  "WebDav",
  "OpenList",
  "AListV3",
  "AList V3",
  "S3",
  "Doge",
  "115 Cloud",
  "115 Open",
  "115 Share",
  "123Pan",
  "123 Open",
  "123PanShare",
  "123PanLink",
  "189Cloud",
  "189CloudPC",
  "189CloudTV",
  "Aliyundrive",
  "AliyundriveOpen",
  "AliyundriveShare",
  "BaiduNetdisk",
  "Cloudreve",
  "Dropbox",
  "GoogleDrive",
  "GooglePhoto",
  "Lanzou",
  "Onedrive",
  "OnedriveAPP",
  "Onedrive Sharelink",
  "PikPak",
  "Quark",
  "QuarkOpen",
  "QuarkTV",
  "UC",
  "UCTV",
  "SFTP",
  "SMB",
  "Thunder",
  "URLTree",
  "USS",
  "Virtual",
  "WPS",
];

const buildDriverInfoMap = () => withAliases({
  ...Object.fromEntries(metadataOnlyNames.map((name) => [name, unsupported(name)])),
  SiYuanWorkspace: {
    common: [field("root_folder_path", "string", "/@workspace", "", false, "SiYuan workspace files exposed through /api/file.")],
    additional: [],
    config: {
      name: "SiYuanWorkspace",
      local_sort: true,
      only_proxy: true,
      no_cache: true,
      no_upload: true,
      need_ms: false,
      default_root: "/@workspace",
      alert: "warning",
      only_indices: false,
      prefer_proxy: true,
      status: "ported",
      note: "Read/list/remove/rename are wired through SiYuan /api/file. Upload is still guarded.",
    },
  },
  WebDav: preferProxy(supported("WebDav", [
    select("vendor", ["sharepoint", "other"], "other"),
    text("address", true),
    text("username", true),
    password("password", true),
    bool("tls_insecure_skip_verify", false),
  ])),
  OpenList: configPatch(supported("OpenList", [
    text("url", true),
    password("meta_password"),
    text("username"),
    password("password"),
    password("token"),
    bool("pass_ip_to_upsteam", true),
    bool("pass_ua_to_upsteam", true),
    bool("forward_archive_requests", true),
    bool("pass_refresh_flag_to_upsteam", false),
  ]), { proxy_range_option: true, link_cache_mode: "auto" }),
  AListV3: supported("AListV3", [
    text("url", true),
    text("username"),
    password("password"),
    password("token"),
  ]),
  "AList V3": supported("AList V3", [
    text("url", true),
    text("username"),
    password("password"),
    password("token"),
  ]),
  S3: configPatch(supported("S3", [
    rootPath("/"),
    text("bucket", true),
    text("endpoint", true),
    text("region"),
    text("access_key_id", true),
    password("secret_access_key", true),
    password("session_token"),
    text("custom_host"),
    bool("enable_custom_host_presign", false),
    number("sign_url_expire", 4),
    text("placeholder"),
    bool("force_path_style", false),
    select("list_object_version", ["v1", "v2"], "v1"),
    bool("remove_bucket", false),
    bool("add_filename_to_disposition", false),
    bool("enable_direct_upload", false),
    text("direct_upload_host"),
  ]), { check_status: true }),
  Doge: configPatch(supported("Doge", [
    rootPath("/"),
    text("bucket", true),
    text("endpoint", true),
    text("region"),
    text("access_key_id", true),
    password("secret_access_key", true),
    password("session_token"),
    text("custom_host"),
    bool("enable_custom_host_presign", false),
    number("sign_url_expire", 4),
    text("placeholder"),
    bool("force_path_style", false),
    select("list_object_version", ["v1", "v2"], "v1"),
    bool("remove_bucket", false),
    bool("add_filename_to_disposition", false),
    bool("enable_direct_upload", false),
    text("direct_upload_host"),
  ]), { check_status: true }),
  "115 Cloud": configPatch(supported("115 Cloud", [
    rootId("0"),
    text("cookie", false, "one of QR code token and cookie required"),
    text("qrcode_token", false, "one of QR code token and cookie required"),
    select("qrcode_source", ["web", "android", "ios", "tv", "alipaymini", "wechatmini", "qandroid"], "web"),
    number("page_size", 1000),
    float("limit_rate", 2),
  ]), {
    link_cache_mode: "ua",
    no_upload: true,
    note: "Runtime ports OpenList 115 Cloud cookie/QR-token login, list/get/read/link, basic management, and storage details. Upload/offline download remain structured placeholders.",
  }),
  "115 Open": configPatch(supported("115 Open", [
    rootId("0"),
    select("order_by", ["file_name", "file_size", "user_utime", "file_type"], "file_name"),
    select("order_direction", ["asc", "desc"], "asc"),
    float("limit_rate", 1),
    number("page_size", 200),
    password("access_token", true),
    password("refresh_token", true),
  ]), {
    default_root: "0",
    link_cache_mode: "ua",
    no_upload: true,
    note: "Runtime ports OpenList 115 Open token refresh, list/get/read/link, basic management, details, and offline add. Upload remains a structured placeholder.",
  }),
  "115 Share": configPatch(supported("115 Share", [
    text("cookie", false, "one of QR code token and cookie required"),
    text("qrcode_token", false, "one of QR code token and cookie required"),
    select("qrcode_source", ["web", "android", "ios", "tv", "alipaymini", "wechatmini", "qandroid"], "web"),
    number("page_size", 1000),
    float("limit_rate", 2),
    text("share_code", true),
    password("receive_code", true),
    rootId("0"),
  ]), {
    default_root: "0",
    link_cache_mode: "ua",
    no_upload: true,
    note: "Runtime ports OpenList 115 Share cookie/QR-token login, list/get/read/link. OpenList marks management and upload as NotSupport.",
  }),
  "123Pan": preferProxy(supported("123Pan", [
    rootId("0"),
    text("username", true),
    password("password", true),
    password("access_token"),
    number("UploadThread", 3),
    field("platform", "string", "web", "", false, "the platform header value, sent with API requests"),
  ])),
  "123 Open": unsupported("123 Open", [
    rootId(),
    text("ClientID"),
    password("ClientSecret"),
    password("AccessToken"),
    password("RefreshToken"),
    bool("use_online_api", true),
    field("api_url_address", "string", "https://api.oplist.org/123cloud/renewapi"),
    number("UploadThread", 3),
    bool("DirectLink", false),
    password("DirectLinkPrivateKey"),
    number("DirectLinkValidDuration", 30),
  ]),
  "123PanShare": unsupported("123PanShare", [text("share_key", true), password("share_pwd"), rootId()]),
  "123PanLink": unsupported("123PanLink", [text("url", true)]),
  "189Cloud": configPatch(supported("189Cloud", [rootId("-11"), text("username", true), password("password", true), text("cookie", false, "Fill in the cookie if need captcha")]), {
    alert: "info|You can try to use 189PC driver if this driver does not work.",
  }),
  "189CloudPC": configPatch(supported("189CloudPC", [
    select("login_type", ["password", "qrcode"], "password", true),
    text("username", true),
    password("password", true),
    text("validate_code"),
    password("access_token"),
    password("refresh_token", false, "To switch accounts, please clear this field"),
    rootId("-11"),
    select("order_by", ["filename", "filesize", "lastOpTime"], "filename"),
    select("order_direction", ["asc", "desc"], "asc"),
    select("type", ["personal", "family"], "personal"),
    text("family_id"),
    select("upload_method", ["stream", "rapid", "old"], "stream"),
    field("upload_thread", "string", "3", "", false, "1<=thread<=32"),
    bool("family_transfer", false),
    bool("rapid_upload", false),
    bool("no_use_ocr", false),
    bool("generate_torrent", false, "Generate torrent file with CAS extension after upload"),
  ]), {
    check_status: true,
    note: "Runtime ports OpenList 189CloudPC QR login, session refresh, family-cloud ID refill, list/get/read/link, and basic management. Password login and upload remain structured placeholders.",
  }),
  "189CloudTV": configPatch(supported("189CloudTV", [
    rootId("-11"),
    password("access_token"),
    select("order_by", ["filename", "filesize", "lastOpTime"], "filename"),
    select("order_direction", ["asc", "desc"], "asc"),
    select("type", ["personal", "family"], "personal"),
    text("family_id"),
    field("upload_thread", "string", "3", "", false, "1<=thread<=32"),
    bool("rapid_upload", false),
  ]), {
    check_status: true,
    note: "Runtime ports OpenList 189CloudTV QR login, session refresh, family-cloud ID refill, list/get/read/link, and basic management. Upload remains a structured placeholder.",
  }),
  Aliyundrive: unsupported("Aliyundrive", [
    rootId("root"),
    password("refresh_token", true),
    select("order_by", ["name", "size", "updated_at", "created_at"]),
    select("order_direction", ["ASC", "DESC"]),
    bool("rapid_upload", false),
    bool("internal_upload", false),
  ]),
  AliyundriveOpen: configPatch(supported("AliyundriveOpen", [
    select("drive_type", ["default", "resource", "backup"], "resource"),
    rootId(),
    password("refresh_token", true),
    select("order_by", ["name", "size", "updated_at", "created_at"]),
    select("order_direction", ["ASC", "DESC"]),
    bool("use_online_api", true),
    select("alipan_type", ["default", "alipanTV"], "default", true),
    field("api_url_address", "string", "https://api.oplist.org/alicloud/renewapi"),
    text("client_id"),
    password("client_secret"),
    select("remove_way", ["trash", "delete"], "trash", true),
    bool("rapid_upload", false),
    bool("internal_upload", false),
    select("livp_download_format", ["jpeg", "mov"], "jpeg"),
    password("access_token"),
  ]), { default_root: "root", no_overwrite_upload: true }),
  AliyundriveShare: unsupported("AliyundriveShare", [
    rootId(),
    password("refresh_token", true),
    text("share_id", true),
    password("share_pwd"),
    select("order_by", ["name", "size", "updated_at", "created_at"]),
    select("order_direction", ["ASC", "DESC"]),
  ]),
  BaiduNetdisk: preferProxy(supported("BaiduNetdisk", [
    rootPath("/"),
    select("order_by", ["name", "time", "size"], "name"),
    select("order_direction", ["asc", "desc"], "asc"),
    select("download_api", ["official", "crack", "crack_video"], "crack_video"),
    bool("use_online_api", true),
    field("api_url_address", "string", "https://api.oplist.org/baiduyun/renewapi"),
    text("client_id"),
    password("client_secret"),
    field("custom_crack_ua", "string", "netdisk", "", true),
    password("access_token"),
    password("refresh_token", true),
    number("upload_thread", 3),
    number("upload_timeout", 60),
    field("upload_api", "string", "https://d.pcs.baidu.com"),
    bool("use_dynamic_upload_api", true),
    number("custom_upload_part_size", 0),
    bool("low_bandwith_upload_mode", false),
    bool("only_list_video_file", false),
  ])),
  Cloudreve: unsupported("Cloudreve", [text("address", true), text("username"), password("password"), password("token")]),
  Dropbox: unsupported("Dropbox", [password("refresh_token", true), text("client_id"), password("client_secret")]),
  GoogleDrive: unsupported("GoogleDrive", [
    rootId(),
    password("refresh_token", true),
    text("order_by", false, "such as: folder,name,modifiedTime"),
    select("order_direction", ["asc", "desc"]),
    bool("use_online_api", true),
    field("api_url_address", "string", "https://api.oplist.org/googleui/renewapi"),
    text("client_id"),
    password("client_secret"),
    number("chunk_size", 5),
    bool("disable_disk_usage", false),
  ]),
  GooglePhoto: unsupported("GooglePhoto", [
    rootId(),
    password("refresh_token", true),
    field("client_id", "string", "202264815644.apps.googleusercontent.com", "", true),
    field("client_secret", "password", "X4Z3ca8xfWDb1Voo-F9a7ZxJ", "", true),
    bool("show_archive", false),
  ]),
  Lanzou: unsupported("Lanzou", [password("cookie", true)]),
  Onedrive: supported("Onedrive", [
    rootPath("/"),
    select("region", ["global", "cn", "us", "de"], "global", true),
    bool("is_sharepoint", false),
    bool("use_online_api", true),
    field("api_url_address", "string", "https://api.oplist.org/onedrive/renewapi"),
    text("client_id"),
    password("client_secret"),
    field("redirect_uri", "string", "https://api.oplist.org/onedrive/callback", "", true),
    password("refresh_token", true),
    text("site_id"),
    number("chunk_size", 5),
    text("custom_host"),
    bool("disable_disk_usage", false),
    bool("enable_direct_upload", false),
  ]),
  OnedriveAPP: unsupported("OnedriveAPP", [
    rootPath("/"),
    select("region", ["global", "cn", "us", "de"], "global", true),
    text("client_id", true),
    password("client_secret", true),
    text("tenant_id"),
    text("email"),
    number("chunk_size", 5),
    text("custom_host"),
    bool("disable_disk_usage", false),
    bool("enable_direct_upload", false),
  ]),
  "Onedrive Sharelink": unsupported("Onedrive Sharelink", [text("share_url", true), rootPath("/")]),
  PikPak: unsupported("PikPak", [text("username", true), password("password", true)]),
  Quark: configPatch(supported("Quark", [
    password("cookie", true),
    rootId("0"),
    select("order_by", ["none", "file_type", "file_name", "updated_at"], "none"),
    select("order_direction", ["asc", "desc"], "asc"),
    bool("use_transcoding_address", false),
    bool("only_list_video_file", false),
    number("addition_version", 2),
  ]), { default_root: "0", no_overwrite_upload: true }),
  UC: configPatch(supported("UC", [
    password("cookie", true),
    rootId("0"),
    select("order_by", ["none", "file_type", "file_name", "updated_at"], "none"),
    select("order_direction", ["asc", "desc"], "asc"),
    bool("use_transcoding_address", false),
    bool("only_list_video_file", false),
    number("addition_version", 2),
  ]), {
    default_root: "0",
    no_overwrite_upload: true,
    only_proxy: true,
  }),
  QuarkOpen: configPatch(supported("QuarkOpen", [
    rootId("0"),
    select("order_by", ["none", "file_type", "file_name", "updated_at", "created_at"], "none"),
    select("order_direction", ["asc", "desc"], "asc"),
    bool("use_online_api", true),
    field("api_url_address", "string", "https://api.oplist.org/quarkyun/renewapi"),
    password("access_token"),
    password("refresh_token", true),
    text("app_id", false, "Built-in public AppID is used when empty"),
    password("sign_key", false, "Built-in public SignKey is used when empty"),
  ]), {
    default_root: "0",
    no_overwrite_upload: true,
    only_proxy: true,
    note: "Runtime ports OpenList QuarkOpen list/get/read/link, basic management, and multipart upload.",
  }),
  QuarkTV: configPatch(supported("QuarkTV", [
    rootId("0"),
    select("order_by", ["file_name", "updated_at"], "updated_at"),
    select("order_direction", ["asc", "desc"], "desc"),
    password("refresh_token"),
    text("device_id"),
    text("query_token", false, "don't edit'"),
    select("link_method", ["download", "streaming"], "streaming", true),
  ]), {
    default_root: "0",
    no_overwrite_upload: true,
    no_upload: true,
    note: "Runtime ports OpenList QuarkTV login token refresh, list/get/read/link. OpenList marks management and upload methods as NotImplement.",
  }),
  UCTV: configPatch(supported("UCTV", [
    rootId("0"),
    select("order_by", ["file_name", "updated_at"], "updated_at"),
    select("order_direction", ["asc", "desc"], "desc"),
    password("refresh_token"),
    text("device_id"),
    text("query_token", false, "don't edit'"),
    select("link_method", ["download", "streaming"], "streaming", true),
  ]), {
    default_root: "0",
    no_overwrite_upload: true,
    no_upload: true,
    note: "Runtime ports OpenList UCTV login token refresh, list/get/read/link. OpenList marks management and upload methods as NotImplement.",
  }),
  SFTP: unsupported("SFTP", [text("address", true), text("username", true), password("password"), password("private_key")]),
  SMB: unsupported("SMB", [text("address", true), text("username"), password("password"), text("share_name")]),
  Thunder: unsupported("Thunder", [text("username"), password("password"), password("refresh_token")]),
  URLTree: unsupported("URLTree", [text("url", true)]),
  USS: unsupported("USS", [text("bucket", true), text("endpoint", true), text("operator", true), password("password", true)]),
  Virtual: unsupported("Virtual", []),
  WPS: configPatch(supported("WPS", [
    rootPath("/"),
    password("cookie", true, "Get Cookie from a fresh or incognito browser session."),
    select("mode", ["Personal", "Business"], "Personal"),
    text("custom_ua", false, "Custom User-Agent copied with the Cookie request."),
  ]), {
    check_status: true,
    no_upload: true,
    note: "Runtime ports OpenList WPS login check, root/group listing, get/read/link, basic management, and storage details. Upload remains a structured placeholder.",
  }),
  Local: configPatch(unsupported("Local", [
    rootPath("/"),
    bool("directory_size", false, "This might impact host performance"),
    bool("thumbnail", false, "enable thumbnail"),
    text("thumb_cache_folder"),
    field("thumb_concurrency", "string", "16", "", false, "Number of concurrent thumbnail generation goroutines."),
    field("video_thumb_pos", "string", "20%", "", false, "The position of the video thumbnail."),
    bool("show_hidden", true, "show hidden directories and files"),
    field("mkdir_perm", "string", "777"),
    field("recycle_bin_path", "string", "delete permanently"),
  ]), {
    no_cache: true,
    no_link_url: true,
    note: "Desktop frontend runtime accesses host fs through Electron. The kernel OpenList HTTP runtime keeps Local metadata only and does not proxy local disks.",
  }),
});

export const driverInfoMap = () => buildDriverInfoMap();

const exposedDriverNames = [
  "SiYuanWorkspace",
  "Local",
  "WebDav",
  "OpenList",
  "AListV3",
  "AList V3",
  "S3",
  "Doge",
  "115 Cloud",
  "115 Open",
  "115 Share",
  "123Pan",
  "189Cloud",
  "189CloudPC",
  "189CloudTV",
  "AliyundriveOpen",
  "BaiduNetdisk",
  "Onedrive",
  "Quark",
  "QuarkOpen",
  "QuarkTV",
  "UC",
  "UCTV",
  "WPS",
];

export const driverNames = () => {
  const map = driverInfoMap();
  return exposedDriverNames.filter((name) => map[name]);
};
