// Generated by scripts/feishu-doc-sync.mjs. Do not edit manually.
export const FEISHU_DOCS = {
  "space": {
    "name": "思盘文档",
    "id": "7663916548666428380"
  },
  "roots": {
    "zh_CN": {
      "readme": "https://my.feishu.cn/wiki/UbRJwiIn9inBeik84wMci78jnve",
      "changelog": "https://my.feishu.cn/wiki/Qvjjw63iMiVwBRkMREfcDuWDnrb",
      "api": "https://my.feishu.cn/wiki/YCDlwD0qJioublkADxOcYVJpnOf",
      "drivers": "https://my.feishu.cn/wiki/Y1gqwvRmwi9mEGk6AHGcGX4OnTg"
    },
    "en_US": {
      "readme": "https://my.feishu.cn/wiki/WHo7wJW48iek2GkJuxmclURtnBc",
      "changelog": "https://my.feishu.cn/wiki/AZHFwEdnrij8sSk2JNfcLrOqnNg",
      "api": "https://my.feishu.cn/wiki/UOk4wIyQIimNjekD5LpcwO1Hnfd",
      "drivers": "https://my.feishu.cn/wiki/BK8BwW7eSiRFzOkuLzoc4zbLnXe"
    }
  },
  "items": {
    "zh_CN": [
      {
        "key": "/更新日志",
        "icon": "#iconList",
        "title": "更新日志",
        "desc": "https://my.feishu.cn/wiki/Qvjjw63iMiVwBRkMREfcDuWDnrb",
        "href": "https://my.feishu.cn/wiki/Qvjjw63iMiVwBRkMREfcDuWDnrb"
      },
      {
        "key": "驱动说明",
        "icon": "#iconFolder",
        "title": "驱动说明",
        "desc": "https://my.feishu.cn/wiki/Y1gqwvRmwi9mEGk6AHGcGX4OnTg",
        "href": "https://my.feishu.cn/wiki/Y1gqwvRmwi9mEGk6AHGcGX4OnTg"
      }
    ],
    "en_US": [
      {
        "key": "/CHANGELOG",
        "icon": "#iconList",
        "title": "CHANGELOG",
        "desc": "https://my.feishu.cn/wiki/AZHFwEdnrij8sSk2JNfcLrOqnNg",
        "href": "https://my.feishu.cn/wiki/AZHFwEdnrij8sSk2JNfcLrOqnNg"
      },
      {
        "key": "Drivers",
        "icon": "#iconFolder",
        "title": "Drivers",
        "desc": "https://my.feishu.cn/wiki/BK8BwW7eSiRFzOkuLzoc4zbLnXe",
        "href": "https://my.feishu.cn/wiki/BK8BwW7eSiRFzOkuLzoc4zbLnXe"
      }
    ]
  },
  "driverDocs": {
    "115": {
      "zh_CN": "https://my.feishu.cn/wiki/XxXqwvlBcip8JJkdH8lcz2vpnuf",
      "en_US": "https://my.feishu.cn/wiki/TURwwfE62idVYekd9oUcB86YnLd"
    },
    "123": {
      "zh_CN": "https://my.feishu.cn/wiki/IY7FwsKh7i0WU3kd0OLcoJIcnzd",
      "en_US": "https://my.feishu.cn/wiki/SV3wwY2u1iPdR0kdQYiccCSNnoh"
    },
    "OpenList": {
      "zh_CN": "https://my.feishu.cn/wiki/UHWbwHFeGiXjGkkTW92cFxynnm3",
      "en_US": "https://my.feishu.cn/wiki/OvQSw8RuniGiEikeU7ecg3BZn8g"
    },
    "AListV3": {
      "zh_CN": "https://my.feishu.cn/wiki/Np9wwXWi3irGOoknwl0cwK7Sn9c",
      "en_US": "https://my.feishu.cn/wiki/LcGGwTSDji3TmgkR4XpcGjYgnZg"
    },
    "S3": {
      "zh_CN": "https://my.feishu.cn/wiki/AlvawbjIuiU22mkDAfLcGdbSnKc",
      "en_US": "https://my.feishu.cn/wiki/SNubwotSci9qIqkHFiTccr7vnib"
    },
    "Doge": {
      "zh_CN": "https://my.feishu.cn/wiki/DUcmwbwxniEOLVkuUVUchknFnmb",
      "en_US": "https://my.feishu.cn/wiki/IlW1wNKqUiMnyWky1FBcWze1n1f"
    },
    "115 Cloud": {
      "zh_CN": "https://my.feishu.cn/wiki/XxXqwvlBcip8JJkdH8lcz2vpnuf",
      "en_US": "https://my.feishu.cn/wiki/TURwwfE62idVYekd9oUcB86YnLd"
    },
    "115 Open": {
      "zh_CN": "https://my.feishu.cn/wiki/SEo2wAbOpi8TTukfLx4cnCw6nre",
      "en_US": "https://my.feishu.cn/wiki/P8uDw6cwIiaLenkCJVtcI2YOnZc"
    },
    "115Open": {
      "zh_CN": "https://my.feishu.cn/wiki/SEo2wAbOpi8TTukfLx4cnCw6nre",
      "en_US": "https://my.feishu.cn/wiki/P8uDw6cwIiaLenkCJVtcI2YOnZc"
    },
    "115 Share": {
      "zh_CN": "https://my.feishu.cn/wiki/TY0FwQyeii2ql4kevuaccuFIn49",
      "en_US": "https://my.feishu.cn/wiki/F5vQw26wEiY40Qkm0D2cW3qSn40"
    },
    "115Share": {
      "zh_CN": "https://my.feishu.cn/wiki/TY0FwQyeii2ql4kevuaccuFIn49",
      "en_US": "https://my.feishu.cn/wiki/F5vQw26wEiY40Qkm0D2cW3qSn40"
    },
    "123Pan": {
      "zh_CN": "https://my.feishu.cn/wiki/IY7FwsKh7i0WU3kd0OLcoJIcnzd",
      "en_US": "https://my.feishu.cn/wiki/SV3wwY2u1iPdR0kdQYiccCSNnoh"
    },
    "189Cloud": {
      "zh_CN": "https://my.feishu.cn/wiki/HBCiwsGnPiEJAvkRD65cjYxLnPg",
      "en_US": "https://my.feishu.cn/wiki/QKtzw9sY2icSakkyy2eciqtunrb"
    },
    "189CloudPC": {
      "zh_CN": "https://my.feishu.cn/wiki/HBCiwsGnPiEJAvkRD65cjYxLnPg",
      "en_US": "https://my.feishu.cn/wiki/QKtzw9sY2icSakkyy2eciqtunrb"
    },
    "189CloudTV": {
      "zh_CN": "https://my.feishu.cn/wiki/HBCiwsGnPiEJAvkRD65cjYxLnPg",
      "en_US": "https://my.feishu.cn/wiki/QKtzw9sY2icSakkyy2eciqtunrb"
    },
    "AliyundriveOpen": {
      "zh_CN": "https://my.feishu.cn/wiki/LQRHwC0BciZFjmkoA7ycwNTknre",
      "en_US": "https://my.feishu.cn/wiki/S5iVwPw2ViXxRzkFgmfcE5yfn3c"
    },
    "AliyunDriveOpen": {
      "zh_CN": "https://my.feishu.cn/wiki/LQRHwC0BciZFjmkoA7ycwNTknre",
      "en_US": "https://my.feishu.cn/wiki/S5iVwPw2ViXxRzkFgmfcE5yfn3c"
    },
    "BaiduNetdisk": {
      "zh_CN": "https://my.feishu.cn/wiki/Gig1wzFKSi0pCbkn1XKcLr8rnvl",
      "en_US": "https://my.feishu.cn/wiki/Jer8wZBafiFEqKktiabciX6anIc"
    },
    "BaiduNetDisk": {
      "zh_CN": "https://my.feishu.cn/wiki/Gig1wzFKSi0pCbkn1XKcLr8rnvl",
      "en_US": "https://my.feishu.cn/wiki/Jer8wZBafiFEqKktiabciX6anIc"
    },
    "GitHub Releases": {
      "zh_CN": "https://my.feishu.cn/wiki/VFiCwOcoOiHKE0kLBJocS3vinIf",
      "en_US": "https://my.feishu.cn/wiki/WEa0wemgEi1vnxkqzrOcIB9snDZ"
    },
    "OneDrive": {
      "zh_CN": "https://my.feishu.cn/wiki/MRpFwCZcQiOpVUkPjjCcdOAvnB2",
      "en_US": "https://my.feishu.cn/wiki/REGUwk92ZiDFWVkHb1yctsQOnPb"
    },
    "Quark": {
      "zh_CN": "https://my.feishu.cn/wiki/Gx06wqy5xiyH6jkENAxcDOxrn5F",
      "en_US": "https://my.feishu.cn/wiki/T8sXwj0oDioIurk2eWmc1MbNnLg"
    },
    "UC": {
      "zh_CN": "https://my.feishu.cn/wiki/Gx06wqy5xiyH6jkENAxcDOxrn5F",
      "en_US": "https://my.feishu.cn/wiki/T8sXwj0oDioIurk2eWmc1MbNnLg"
    },
    "QuarkOpen": {
      "zh_CN": "https://my.feishu.cn/wiki/Gx06wqy5xiyH6jkENAxcDOxrn5F",
      "en_US": "https://my.feishu.cn/wiki/T8sXwj0oDioIurk2eWmc1MbNnLg"
    },
    "QuarkTV": {
      "zh_CN": "https://my.feishu.cn/wiki/Gx06wqy5xiyH6jkENAxcDOxrn5F",
      "en_US": "https://my.feishu.cn/wiki/T8sXwj0oDioIurk2eWmc1MbNnLg"
    },
    "UCTV": {
      "zh_CN": "https://my.feishu.cn/wiki/Gx06wqy5xiyH6jkENAxcDOxrn5F",
      "en_US": "https://my.feishu.cn/wiki/T8sXwj0oDioIurk2eWmc1MbNnLg"
    },
    "WPS": {
      "zh_CN": "https://my.feishu.cn/wiki/QXhCwMFztiGy16kCIl1cMqZWnLe",
      "en_US": "https://my.feishu.cn/wiki/S5ovwL0bSiD7TNkwFmtcZwDqnXb"
    },
    "Local": {
      "zh_CN": "https://my.feishu.cn/wiki/Q6s7wW4LRi7CZLkeNZkcbAJjnth",
      "en_US": "https://my.feishu.cn/wiki/PsdzwWqDbiUqAakFw1Ec1URVnYb"
    },
    "SiYuanWorkspace": {
      "zh_CN": "https://my.feishu.cn/wiki/OpSrwXiUniBI7akO94ocSpqTnjc",
      "en_US": "https://my.feishu.cn/wiki/LUo2wmM67ixlQ5k2RXLcecngnfe"
    },
    "WebDav": {
      "zh_CN": "https://my.feishu.cn/wiki/JJ4Pw3NRVi19AekGbY8cWFNcnmg",
      "en_US": "https://my.feishu.cn/wiki/LIOBw9j2uiSpaqkXGw5c9wvRnOh"
    }
  }
} as const
